name: mansfield-gpx-analysis

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.6.7
  - matplotlib
  - pandas
  - geopandas
  - gpxpy
  - pandoc
  - make

# Jupyter Environment
#  - autopep8
#  - jupyterlab
#  - notebook
# Need these?
#  - jupyter_contrib_nbextensions
#  - nbclean
