name: mansfield-gpx-analysis

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.8.2
  - matplotlib
  - pandas
  - geopandas
  - gpxpy
  - pandoc
  - make
  - autopep8
  - jupyterlab
  - notebook
  - jupyter_contrib_nbextensions
  - nbclean
